### ISSUE TITLE
Add user profile to chat message

### ISSUE THREAD

**Issue by Kennygunderman** [Kennygunderman/snack_chat#13]
A new user object should be created upon registering.
User username should appear in the chat

### Tasks
 - [x] Create user document
     - [x] email
     - [x] username (default this to email before @) and trim to 7 chars
 - [x] Create user on login/signup
 - [x] Username initial should be chat profile pic
