### ISSUE TITLE
User auth with email and password

### ISSUE THREAD

**Issue by Kennygunderman** [Kennygunderman/snack_chat#2]
Users should be able to sign up/log in with an email and password.

###Tasks:
- [x] Basic pw validation
    - [x] > 6 characters
    - [x] password match
- [x] Connect to firebase for auth
- [x] User can create an account
- [x] User can login with created account
- [x] Error message for invalid credentials

**Comment by Kennygunderman** [comment]
PR here: https://github.com/Kennygunderman/snack_chat/pull/5
